blueprint:
  name: Sonoff Smart Climate Control
  description: >
    Intelligent control of Sonoff thermostats with external temperature sensors.
    
    **Features:**
    - Automatic detection of all required entities
    - Simple configuration: Just select thermostats and sensors
    - Control single or multiple thermostats
    - One or multiple temperature sensors (average calculated for multiple sensors)
    - Optional: Window detection for automatic heating control
    - Configurable update intervals and temperature limits
    
    Flexible for single rooms or large zones with multiple radiators.
  domain: automation
  author: EyJunge1
  source_url: https://github.com/eyjunge1/ha-sonoff-smart-climate/blob/main/blueprint.yml
  homeassistant:
    min_version: 2024.6.0
  
  input:
    # ==================== THERMOSTAT ====================
    thermostat_section:
      name: Thermostat Configuration
      icon: mdi:thermostat
      description: >
        Select one or multiple thermostats and the associated sensors.
        For multiple thermostats, all will be controlled synchronously.
      input:
        thermostats:
          name: Thermostat(s)
          description: >
            One or multiple Sonoff thermostats.
            For multiple thermostats, all will receive the same temperature.
          selector:
            entity:
              multiple: true
              filter:
                - domain: climate
        
        temp_sensors:
          name: Temperature Sensor(s)
          description: >
            One or multiple external temperature sensors (e.g. Aqara, Zigbee).
            For multiple sensors, the average temperature will be calculated.
          selector:
            entity:
              multiple: true
              filter:
                - domain: sensor
                  device_class: temperature
    
    # ==================== SETTINGS ====================
    settings_section:
      name: Settings
      icon: mdi:cog
      description: Configure the behavior of synchronization
      collapsed: true
      input:
        update_interval:
          name: Update Interval
          description: How often should the temperature be synchronized (in seconds)
          default: 30
          selector:
            number:
              min: 10
              max: 300
              step: 5
              unit_of_measurement: s
              mode: slider
        
        temp_min:
          name: Minimum Temperature
          description: Temperature values below this value will be ignored as invalid
          default: 0
          selector:
            number:
              min: -10
              max: 15
              step: 1
              unit_of_measurement: °C
        
        temp_max:
          name: Maximum Temperature
          description: Temperature values above this value will be ignored as invalid
          default: 50
          selector:
            number:
              min: 30
              max: 60
              step: 1
              unit_of_measurement: °C
        
        round_precision:
          name: Rounding Precision
          description: How many decimal places to round to
          default: 1
          selector:
            number:
              min: 0
              max: 2
              step: 1
    
    # ==================== WINDOW DETECTION (Optional) ====================
    window_section:
      name: Window Detection (Optional)
      icon: mdi:window-open
      description: >
        Automatic heating control with open windows.
        For multiple thermostats, all will be notified.
      collapsed: true
      input:
        enable_window_detection:
          name: Enable Window Detection
          description: Enable automatic detection of open windows
          default: false
          selector:
            boolean:
        
        window_sensors:
          name: Window Contacts
          description: >
            Select all window and door contacts for this room.
            As soon as one of them is opened, the thermostat switches to "Open Window" mode.
          default: []
          selector:
            entity:
              multiple: true
              filter:
                - domain: binary_sensor
                  device_class:
                    - window
                    - door
                    - opening

variables:
  thermostats: !input thermostats
  temp_sensors: !input temp_sensors
  temp_min: !input temp_min
  temp_max: !input temp_max
  round_precision: !input round_precision
  enable_window: !input enable_window_detection
  window_sensors: !input window_sensors
  
  # Convert thermostats to list
  thermostat_list: >
    {% if thermostats is string %}
      {{ [thermostats] }}
    {% else %}
      {{ thermostats }}
    {% endif %}
  
  # Automatically find the associated External Temperature Input entities
  temp_input_list: >
    {% set ns = namespace(inputs=[]) %}
    {% if thermostats is string %}
      {% set tlist = [thermostats] %}
    {% else %}
      {% set tlist = thermostats %}
    {% endif %}
    {% for thermostat in tlist %}
      {% set device_id = device_id(thermostat) %}
      {% if device_id %}
        {% set entities = device_entities(device_id) %}
        {% for entity in entities %}
          {% if 'external_temperature_input' in entity and not ('_2' in entity or '_3' in entity) %}
            {% set ns.inputs = ns.inputs + [entity] %}
          {% endif %}
        {% endfor %}
      {% endif %}
    {% endfor %}
    {{ ns.inputs }}
  
  # Automatically find the associated Temperature Sensor Select entities
  temp_sensor_select_list: >
    {% set ns = namespace(selects=[]) %}
    {% if thermostats is string %}
      {% set tlist = [thermostats] %}
    {% else %}
      {% set tlist = thermostats %}
    {% endif %}
    {% for thermostat in tlist %}
      {% set device_id = device_id(thermostat) %}
      {% if device_id %}
        {% set entities = device_entities(device_id) %}
        {% for entity in entities %}
          {% if 'temperature_sensor' in entity and states[entity].domain == 'select' %}
            {% set ns.selects = ns.selects + [entity] %}
          {% endif %}
        {% endfor %}
      {% endif %}
    {% endfor %}
    {{ ns.selects }}
  
  # Automatically find the associated Open Window Switch entities
  window_switch_list: >
    {% set ns = namespace(switches=[]) %}
    {% if thermostats is string %}
      {% set tlist = [thermostats] %}
    {% else %}
      {% set tlist = thermostats %}
    {% endif %}
    {% for thermostat in tlist %}
      {% set device_id = device_id(thermostat) %}
      {% if device_id %}
        {% set entities = device_entities(device_id) %}
        {% for entity in entities %}
          {% if 'open_window' in entity and states[entity].domain == 'switch' %}
            {% set ns.switches = ns.switches + [entity] %}
          {% endif %}
        {% endfor %}
      {% endif %}
    {% endfor %}
    {{ ns.switches }}

triggers:
  - trigger: time_pattern
    seconds: "/30"
  - trigger: homeassistant
    event: start
  - trigger: state
    entity_id: !input temp_sensors

condition: []

actions:
  # ==================== CALCULATE AVERAGE TEMPERATURE ====================
  - variables:
      # Collect all valid temperature values
      valid_temps: >
        {% set ns = namespace(temps=[]) %}
        {% if temp_sensors is string %}
          {% set sensor_list = [temp_sensors] %}
        {% else %}
          {% set sensor_list = temp_sensors %}
        {% endif %}
        {% for sensor in sensor_list %}
          {% set temp = states(sensor) | float(0) %}
          {% if temp >= temp_min and temp <= temp_max %}
            {% set ns.temps = ns.temps + [temp] %}
          {% endif %}
        {% endfor %}
        {{ ns.temps }}
      
      # Calculate average
      avg_temp: >
        {% if valid_temps | length > 0 %}
          {{ (valid_temps | sum / valid_temps | length) | round(round_precision) }}
        {% else %}
          {{ 0 }}
        {% endif %}
  
  # Check if we have valid temperatures
  - condition: template
    value_template: "{{ valid_temps | length > 0 and avg_temp | float > 0 }}"
  
  # ==================== SET TEMPERATURE SENSOR TO "EXTERNAL" ====================
  - repeat:
      count: "{{ temp_sensor_select_list | length }}"
      sequence:
        - variables:
            current_index: "{{ repeat.index - 1 }}"
            current_sensor_select: "{{ temp_sensor_select_list[current_index] }}"
        
        - action: select.select_option
          target:
            entity_id: "{{ current_sensor_select }}"
          data:
            option: "external"
  
  # ==================== SEND TEMPERATURE TO ALL THERMOSTATS ====================
  - repeat:
      count: "{{ temp_input_list | length }}"
      sequence:
        - variables:
            current_index: "{{ repeat.index - 1 }}"
            current_temp_input: "{{ temp_input_list[current_index] }}"
        
        - action: number.set_value
          target:
            entity_id: "{{ current_temp_input }}"
          data:
            value: "{{ avg_temp }}"
  
  # ==================== WINDOW DETECTION ====================
  - condition: template
    value_template: "{{ enable_window and window_switch_list and window_switch_list | length > 0 and window_sensors and window_sensors | length > 0 }}"
  
  - variables:
      # Check if ANY window is open
      any_window_open: >
        {{ expand(window_sensors) | selectattr('state', 'in', ['on', 'open']) | list | count > 0 }}
  
  # Set ALL window switches
  - repeat:
      count: "{{ window_switch_list | length }}"
      sequence:
        - variables:
            current_index: "{{ repeat.index - 1 }}"
            current_switch: "{{ window_switch_list[current_index] }}"
        
        - action: "switch.turn_{{ 'on' if any_window_open else 'off' }}"
          target:
            entity_id: "{{ current_switch }}"

mode: single
max_exceeded: silent
