blueprint:
  name: Sonoff Smart Climate Control
  description: >
    Intelligente Steuerung von Sonoff Thermostaten mit externen Temperatursensoren.
    
    **Features:**
    - Einzelnes oder mehrere Thermostate steuern
    - Ein oder mehrere Temperatursensoren (Durchschnitt bei mehreren)
    - Optional: Fenster-Erkennung für automatische Heizungssteuerung
    - Konfigurierbare Update-Intervalle und Temperatur-Grenzen
    
    Flexibel für einzelne Räume oder große Zonen mit mehreren Heizkörpern.
  domain: automation
  author: EyJunge1
  source_url: https://github.com/eyjunge1/ha-sonoff-smart-climate/blob/main/blueprint.yml
  homeassistant:
    min_version: 2024.6.0
  
  input:
    # ==================== THERMOSTAT ====================
    thermostat_section:
      name: Thermostat Konfiguration
      icon: mdi:thermostat
      description: >
        Wähle ein oder mehrere Thermostate und die zugehörigen Sensoren.
        Bei mehreren Thermostaten werden alle synchron gesteuert.
      input:
        thermostats:
          name: Thermostat(e)
          description: >
            Ein oder mehrere Sonoff Thermostate.
            Bei mehreren werden alle mit der gleichen Temperatur versorgt.
          selector:
            entity:
              filter:
                - domain: climate
              multiple: true
        
        temp_inputs:
          name: External Temperature Input(s)
          description: >
            Die "External Temperature Input" Entität(en) der Thermostate.
            WICHTIG: Reihenfolge muss mit den Thermostaten übereinstimmen!
          selector:
            entity:
              filter:
                - domain: number
              multiple: true
        
        temp_sensors:
          name: Temperatursensor(en)
          description: >
            Ein oder mehrere externe Temperatursensoren (z.B. Aqara, Zigbee).
            Bei mehreren wird die Durchschnittstemperatur berechnet.
          selector:
            entity:
              filter:
                - domain: sensor
                  device_class: temperature
              multiple: true
    
    # ==================== EINSTELLUNGEN ====================
    settings_section:
      name: Einstellungen
      icon: mdi:cog
      description: Konfiguriere das Verhalten der Synchronisierung
      collapsed: true
      input:
        update_interval:
          name: Update Interval
          description: Wie oft soll die Temperatur synchronisiert werden (in Sekunden)
          default: 30
          selector:
            number:
              min: 10
              max: 300
              step: 5
              unit_of_measurement: s
              mode: slider
        
        temp_min:
          name: Minimale Temperatur
          description: Temperaturwerte unter diesem Wert werden als ungültig ignoriert
          default: 0
          selector:
            number:
              min: -10
              max: 15
              step: 1
              unit_of_measurement: °C
        
        temp_max:
          name: Maximale Temperatur
          description: Temperaturwerte über diesem Wert werden als ungültig ignoriert
          default: 50
          selector:
            number:
              min: 30
              max: 60
              step: 1
              unit_of_measurement: °C
        
        round_precision:
          name: Rundungs-Präzision
          description: Auf wie viele Nachkommastellen soll gerundet werden
          default: 1
          selector:
            number:
              min: 0
              max: 2
              step: 1
    
    # ==================== FENSTER-ERKENNUNG (Optional) ====================
    window_section:
      name: Fenster-Erkennung (Optional)
      icon: mdi:window-open
      description: >
        Automatische Heizungssteuerung bei offenen Fenstern.
        Bei mehreren Thermostaten werden alle benachrichtigt.
      collapsed: true
      input:
        enable_window_detection:
          name: Fenster-Erkennung aktivieren
          description: Aktiviere die automatische Erkennung offener Fenster
          default: false
          selector:
            boolean:
        
        window_switches:
          name: Window Switch(es)
          description: >
            Die "Open Window Switch" Entität(en) der Thermostate.
            WICHTIG: Reihenfolge muss mit den Thermostaten übereinstimmen!
          default: []
          selector:
            entity:
              filter:
                - domain: switch
              multiple: true
        
        window_sensors:
          name: Fensterkontakte
          description: >
            Wähle alle Fenster- und Türkontakte.
            Sobald einer davon geöffnet wird, werden alle Window Switches aktiviert.
          default: []
          selector:
            entity:
              filter:
                - domain: binary_sensor
                  device_class:
                    - window
                    - door
                    - opening
              multiple: true

variables:
  thermostats: !input thermostats
  temp_inputs: !input temp_inputs
  temp_sensors: !input temp_sensors
  temp_min: !input temp_min
  temp_max: !input temp_max
  round_precision: !input round_precision
  enable_window: !input enable_window_detection
  window_switches: !input window_switches
  window_sensors: !input window_sensors

triggers:
  - trigger: time_pattern
    seconds: "/30"
  - trigger: homeassistant
    event: start
  - trigger: state
    entity_id: !input temp_sensors

condition: []

actions:
  # ==================== DURCHSCHNITTSTEMPERATUR BERECHNEN ====================
  - variables:
      # Sammle alle gültigen Temperaturwerte
      valid_temps: >
        {% set ns = namespace(temps=[]) %}
        {% if temp_sensors is string %}
          {% set sensor_list = [temp_sensors] %}
        {% else %}
          {% set sensor_list = temp_sensors %}
        {% endif %}
        {% for sensor in sensor_list %}
          {% set temp = states(sensor) | float(0) %}
          {% if temp >= temp_min and temp <= temp_max %}
            {% set ns.temps = ns.temps + [temp] %}
          {% endif %}
        {% endfor %}
        {{ ns.temps }}
      
      # Berechne Durchschnitt
      avg_temp: >
        {% if valid_temps | length > 0 %}
          {{ (valid_temps | sum / valid_temps | length) | round(round_precision) }}
        {% else %}
          {{ 0 }}
        {% endif %}
      
      # Konvertiere zu Liste falls nötig
      thermostat_list: >
        {% if thermostats is string %}
          {{ [thermostats] }}
        {% else %}
          {{ thermostats }}
        {% endif %}
      
      temp_input_list: >
        {% if temp_inputs is string %}
          {{ [temp_inputs] }}
        {% else %}
          {{ temp_inputs }}
        {% endif %}
  
  # Prüfe ob wir gültige Temperaturen haben
  - condition: template
    value_template: "{{ valid_temps | length > 0 and avg_temp | float > 0 }}"
  
  # ==================== TEMPERATUR AN ALLE THERMOSTATE SENDEN ====================
  - repeat:
      count: "{{ temp_input_list | length }}"
      sequence:
        - variables:
            current_index: "{{ repeat.index - 1 }}"
            current_temp_input: "{{ temp_input_list[current_index] }}"
        
        - action: number.set_value
          target:
            entity_id: "{{ current_temp_input }}"
          data:
            value: "{{ avg_temp }}"
  
  # ==================== FENSTER-ERKENNUNG ====================
  - condition: template
    value_template: "{{ enable_window and window_switches and window_switches | length > 0 and window_sensors and window_sensors | length > 0 }}"
  
  - variables:
      # Prüfe ob IRGENDEIN Fenster offen ist
      any_window_open: >
        {{ expand(window_sensors) | selectattr('state', 'in', ['on', 'open']) | list | count > 0 }}
      
      window_switch_list: >
        {% if window_switches is string %}
          {{ [window_switches] }}
        {% else %}
          {{ window_switches }}
        {% endif %}
  
  # Setze ALLE Window Switches
  - repeat:
      count: "{{ window_switch_list | length }}"
      sequence:
        - variables:
            current_index: "{{ repeat.index - 1 }}"
            current_switch: "{{ window_switch_list[current_index] }}"
        
        - action: "switch.turn_{{ 'on' if any_window_open else 'off' }}"
          target:
            entity_id: "{{ current_switch }}"

mode: single
max_exceeded: silent
