blueprint:
  name: Sonoff Smart Climate Control
  description: >
    Intelligente Steuerung von Sonoff Thermostaten mit externen Temperatursensoren.
    
    **Features:**
    - Automatische Erkennung aller benötigten Entitäten
    - Einfache Konfiguration: Nur Thermostate und Sensoren auswählen
    - Einzelnes oder mehrere Thermostate steuern
    - Ein oder mehrere Temperatursensoren (Durchschnitt bei mehreren)
    - Optional: Fenster-Erkennung für automatische Heizungssteuerung
    - Konfigurierbare Update-Intervalle und Temperatur-Grenzen
    
    Flexibel für einzelne Räume oder große Zonen mit mehreren Heizkörpern.
  domain: automation
  author: EyJunge1
  source_url: https://github.com/eyjunge1/ha-sonoff-smart-climate/blob/main/blueprint.yml
  homeassistant:
    min_version: 2024.6.0
  
  input:
    # ==================== THERMOSTAT ====================
    thermostat_section:
      name: Thermostat Konfiguration
      icon: mdi:thermostat
      description: >
        Wähle ein oder mehrere Thermostate und die zugehörigen Sensoren.
        Bei mehreren Thermostaten werden alle synchron gesteuert.
      input:
        thermostats:
          name: Thermostat(e)
          description: >
            Ein oder mehrere Sonoff Thermostate.
            Bei mehreren werden alle mit der gleichen Temperatur versorgt.
          selector:
            entity:
              multiple: true
              filter:
                - domain: climate
        
        temp_sensors:
          name: Temperatursensor(en)
          description: >
            Ein oder mehrere externe Temperatursensoren (z.B. Aqara, Zigbee).
            Bei mehreren wird die Durchschnittstemperatur berechnet.
          selector:
            entity:
              multiple: true
              filter:
                - domain: sensor
                  device_class: temperature
    
    # ==================== EINSTELLUNGEN ====================
    settings_section:
      name: Einstellungen
      icon: mdi:cog
      description: Konfiguriere das Verhalten der Synchronisierung
      collapsed: true
      input:
        update_interval:
          name: Update Interval
          description: Wie oft soll die Temperatur synchronisiert werden (in Sekunden)
          default: 30
          selector:
            number:
              min: 10
              max: 300
              step: 5
              unit_of_measurement: s
              mode: slider
        
        temp_min:
          name: Minimale Temperatur
          description: Temperaturwerte unter diesem Wert werden als ungültig ignoriert
          default: 0
          selector:
            number:
              min: -10
              max: 15
              step: 1
              unit_of_measurement: °C
        
        temp_max:
          name: Maximale Temperatur
          description: Temperaturwerte über diesem Wert werden als ungültig ignoriert
          default: 50
          selector:
            number:
              min: 30
              max: 60
              step: 1
              unit_of_measurement: °C
        
        round_precision:
          name: Rundungs-Präzision
          description: Auf wie viele Nachkommastellen soll gerundet werden
          default: 1
          selector:
            number:
              min: 0
              max: 2
              step: 1
    
    # ==================== FENSTER-ERKENNUNG (Optional) ====================
    window_section:
      name: Fenster-Erkennung (Optional)
      icon: mdi:window-open
      description: >
        Automatische Heizungssteuerung bei offenen Fenstern.
        Bei mehreren Thermostaten werden alle benachrichtigt.
      collapsed: true
      input:
        enable_window_detection:
          name: Fenster-Erkennung aktivieren
          description: Aktiviere die automatische Erkennung offener Fenster
          default: false
          selector:
            boolean:
        
        window_sensors:
          name: Fensterkontakte
          description: >
            Wähle alle Fenster- und Türkontakte für diesen Raum.
            Sobald einer davon geöffnet wird, schaltet das Thermostat in den "Open Window" Modus.
          default: []
          selector:
            entity:
              multiple: true
              filter:
                - domain: binary_sensor
                  device_class:
                    - window
                    - door
                    - opening

variables:
  thermostats: !input thermostats
  temp_sensors: !input temp_sensors
  temp_min: !input temp_min
  temp_max: !input temp_max
  round_precision: !input round_precision
  enable_window: !input enable_window_detection
  window_sensors: !input window_sensors
  
  # Konvertiere Thermostats zu Liste
  thermostat_list: >
    {% if thermostats is string %}
      {{ [thermostats] }}
    {% else %}
      {{ thermostats }}
    {% endif %}
  
  # Finde automatisch die zugehörigen External Temperature Input Entitäten
  temp_input_list: >
    {% set ns = namespace(inputs=[]) %}
    {% if thermostats is string %}
      {% set tlist = [thermostats] %}
    {% else %}
      {% set tlist = thermostats %}
    {% endif %}
    {% for thermostat in tlist %}
      {% set device_id = device_id(thermostat) %}
      {% if device_id %}
        {% set entities = device_entities(device_id) %}
        {% for entity in entities %}
          {% if 'external_temperature_input' in entity and not ('_2' in entity or '_3' in entity) %}
            {% set ns.inputs = ns.inputs + [entity] %}
          {% endif %}
        {% endfor %}
      {% endif %}
    {% endfor %}
    {{ ns.inputs }}
  
  # Finde automatisch die zugehörigen Temperature Sensor Select Entitäten
  temp_sensor_select_list: >
    {% set ns = namespace(selects=[]) %}
    {% if thermostats is string %}
      {% set tlist = [thermostats] %}
    {% else %}
      {% set tlist = thermostats %}
    {% endif %}
    {% for thermostat in tlist %}
      {% set device_id = device_id(thermostat) %}
      {% if device_id %}
        {% set entities = device_entities(device_id) %}
        {% for entity in entities %}
          {% if 'temperature_sensor' in entity and states[entity].domain == 'select' %}
            {% set ns.selects = ns.selects + [entity] %}
          {% endif %}
        {% endfor %}
      {% endif %}
    {% endfor %}
    {{ ns.selects }}
  
  # Finde automatisch die zugehörigen Open Window Switch Entitäten
  window_switch_list: >
    {% set ns = namespace(switches=[]) %}
    {% if thermostats is string %}
      {% set tlist = [thermostats] %}
    {% else %}
      {% set tlist = thermostats %}
    {% endif %}
    {% for thermostat in tlist %}
      {% set device_id = device_id(thermostat) %}
      {% if device_id %}
        {% set entities = device_entities(device_id) %}
        {% for entity in entities %}
          {% if 'open_window' in entity and states[entity].domain == 'switch' %}
            {% set ns.switches = ns.switches + [entity] %}
          {% endif %}
        {% endfor %}
      {% endif %}
    {% endfor %}
    {{ ns.switches }}

triggers:
  - trigger: time_pattern
    seconds: "/30"
  - trigger: homeassistant
    event: start
  - trigger: state
    entity_id: !input temp_sensors

condition: []

actions:
  # ==================== DURCHSCHNITTSTEMPERATUR BERECHNEN ====================
  - variables:
      # Sammle alle gültigen Temperaturwerte
      valid_temps: >
        {% set ns = namespace(temps=[]) %}
        {% if temp_sensors is string %}
          {% set sensor_list = [temp_sensors] %}
        {% else %}
          {% set sensor_list = temp_sensors %}
        {% endif %}
        {% for sensor in sensor_list %}
          {% set temp = states(sensor) | float(0) %}
          {% if temp >= temp_min and temp <= temp_max %}
            {% set ns.temps = ns.temps + [temp] %}
          {% endif %}
        {% endfor %}
        {{ ns.temps }}
      
      # Berechne Durchschnitt
      avg_temp: >
        {% if valid_temps | length > 0 %}
          {{ (valid_temps | sum / valid_temps | length) | round(round_precision) }}
        {% else %}
          {{ 0 }}
        {% endif %}
  
  # Prüfe ob wir gültige Temperaturen haben
  - condition: template
    value_template: "{{ valid_temps | length > 0 and avg_temp | float > 0 }}"
  
  # ==================== TEMPERATURSENSOR AUF "EXTERNAL" SETZEN ====================
  - repeat:
      count: "{{ temp_sensor_select_list | length }}"
      sequence:
        - variables:
            current_index: "{{ repeat.index - 1 }}"
            current_sensor_select: "{{ temp_sensor_select_list[current_index] }}"
        
        - action: select.select_option
          target:
            entity_id: "{{ current_sensor_select }}"
          data:
            option: "external"
  
  # ==================== TEMPERATUR AN ALLE THERMOSTATE SENDEN ====================
  - repeat:
      count: "{{ temp_input_list | length }}"
      sequence:
        - variables:
            current_index: "{{ repeat.index - 1 }}"
            current_temp_input: "{{ temp_input_list[current_index] }}"
        
        - action: number.set_value
          target:
            entity_id: "{{ current_temp_input }}"
          data:
            value: "{{ avg_temp }}"
  
  # ==================== FENSTER-ERKENNUNG ====================
  - condition: template
    value_template: "{{ enable_window and window_switch_list and window_switch_list | length > 0 and window_sensors and window_sensors | length > 0 }}"
  
  - variables:
      # Prüfe ob IRGENDEIN Fenster offen ist
      any_window_open: >
        {{ expand(window_sensors) | selectattr('state', 'in', ['on', 'open']) | list | count > 0 }}
  
  # Setze ALLE Window Switches
  - repeat:
      count: "{{ window_switch_list | length }}"
      sequence:
        - variables:
            current_index: "{{ repeat.index - 1 }}"
            current_switch: "{{ window_switch_list[current_index] }}"
        
        - action: "switch.turn_{{ 'on' if any_window_open else 'off' }}"
          target:
            entity_id: "{{ current_switch }}"

mode: single
max_exceeded: silent
